//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afiliado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Afiliado()
        {
            this.Compra = new HashSet<Compra>();
            this.CambioPlan = new HashSet<CambioPlan>();
            this.Turno = new HashSet<Turno>();
        }
    
        public int Usuario_Id { get; set; }
        public string Estado_Civil { get; set; }
        public Nullable<decimal> Plan_Codigo { get; set; }
        public Nullable<decimal> Cantidad_Hijos { get; set; }
        public int Numero_Familia { get; set; }
        public decimal Numero_Miembro { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<System.DateTime> Fecha_Baja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual PlanAfiliado PlanAfiliado { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CambioPlan> CambioPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turno> Turno { get; set; }
    }
}
