//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambioPlan
    {
        public int Id_CambioPlan { get; set; }
        public Nullable<int> Usuario_Id { get; set; }
        public System.DateTime Fecha_Cambio { get; set; }
        public decimal Plan_Viejo_Codigo { get; set; }
        public decimal Plan_Nuevo_Codigo { get; set; }
        public string Motivo { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
        public virtual PlanAfiliado PlanAfiliado { get; set; }
        public virtual PlanAfiliado PlanAfiliado1 { get; set; }
    }
}
