//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancelacion
    {
        public int Id_Cancelacion { get; set; }
        public decimal Turno_Id { get; set; }
        public Nullable<int> Tipo_Id { get; set; }
        public string Motivo { get; set; }
    
        public virtual TipoCancelacion TipoCancelacion { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
