//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicaNetDBEntities1 : DbContext
    {
        public ClinicaNetDBEntities1()
            : base("name=ClinicaNetDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afiliado> Afiliado { get; set; }
        public virtual DbSet<Agenda> Agenda { get; set; }
        public virtual DbSet<Atencion> Atencion { get; set; }
        public virtual DbSet<BonoConsulta> BonoConsulta { get; set; }
        public virtual DbSet<BonoFarmacia> BonoFarmacia { get; set; }
        public virtual DbSet<CambioPlan> CambioPlan { get; set; }
        public virtual DbSet<Cancelacion> Cancelacion { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<Dia> Dia { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<EspecialidadXProfesional> EspecialidadXProfesional { get; set; }
        public virtual DbSet<Funcionalidad> Funcionalidad { get; set; }
        public virtual DbSet<LoginUsuario> LoginUsuario { get; set; }
        public virtual DbSet<MedicamentoXReceta> MedicamentoXReceta { get; set; }
        public virtual DbSet<PlanAfiliado> PlanAfiliado { get; set; }
        public virtual DbSet<Profesional> Profesional { get; set; }
        public virtual DbSet<Receta> Receta { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TipoCancelacion> TipoCancelacion { get; set; }
        public virtual DbSet<TipoEspecialidad> TipoEspecialidad { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
