//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicaNetDBEntities : DbContext
    {
        public ClinicaNetDBEntities()
            : base("name=ClinicaNetDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afiliado> Afiliadoes { get; set; }
        public virtual DbSet<Agendum> Agenda { get; set; }
        public virtual DbSet<Atencion> Atencions { get; set; }
        public virtual DbSet<BonoConsulta> BonoConsultas { get; set; }
        public virtual DbSet<BonoFarmacia> BonoFarmacias { get; set; }
        public virtual DbSet<CambioPlan> CambioPlans { get; set; }
        public virtual DbSet<Cancelacion> Cancelacions { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<Consulta> Consultas { get; set; }
        public virtual DbSet<Dia> Dias { get; set; }
        public virtual DbSet<Especialidad> Especialidads { get; set; }
        public virtual DbSet<EspecialidadXProfesional> EspecialidadXProfesionals { get; set; }
        public virtual DbSet<Funcionalidad> Funcionalidads { get; set; }
        public virtual DbSet<LoginUsuario> LoginUsuarios { get; set; }
        public virtual DbSet<MedicamentoXReceta> MedicamentoXRecetas { get; set; }
        public virtual DbSet<PlanAfiliado> PlanAfiliadoes { get; set; }
        public virtual DbSet<Profesional> Profesionals { get; set; }
        public virtual DbSet<Receta> Recetas { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<TipoCancelacion> TipoCancelacions { get; set; }
        public virtual DbSet<TipoEspecialidad> TipoEspecialidads { get; set; }
        public virtual DbSet<Turno> Turnoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
