//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receta()
        {
            this.MedicamentoXReceta = new HashSet<MedicamentoXReceta>();
        }
    
        public int Atencion_Id { get; set; }
        public Nullable<decimal> Bono_Farmacia_Numero { get; set; }
        public decimal Id_Receta { get; set; }
    
        public virtual Atencion Atencion { get; set; }
        public virtual BonoFarmacia BonoFarmacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicamentoXReceta> MedicamentoXReceta { get; set; }
    }
}
