//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turno()
        {
            this.Cancelacion = new HashSet<Cancelacion>();
            this.Consulta = new HashSet<Consulta>();
        }
    
        public decimal Id_Turno { get; set; }
        public Nullable<System.DateTime> Pedido_Fecha_Hora { get; set; }
        public Nullable<int> Afiliado_Usuario_Id { get; set; }
        public int Profesional_Usuario_Id { get; set; }
        public decimal Especialidad_Id { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public Nullable<System.DateTime> Turno_Fecha_Hora { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancelacion> Cancelacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual EspecialidadXProfesional EspecialidadXProfesional { get; set; }
    }
}
