//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id_Usuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Tipo_Documento { get; set; }
        public decimal Numero_Documento { get; set; }
        public string Direccion { get; set; }
        public Nullable<decimal> Telefono { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> Fecha_Nac { get; set; }
        public string Sexo { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
        public virtual LoginUsuario LoginUsuario { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
